sbp:
  version: "v1.0.0"
  description: |-
    creating voucher system
    with spring boot

spring:
  datasource:
    url: jdbc:mysql://localhost/voucherDB
    username: root
    password: voucher1234!